### ISSUE TITLE
Feature Request: Integration with corfu-doc

### ISSUE THREAD

**Issue by anonimitoraf** [manateelazycat/lsp-bridge#140] opened 2022-05-25 11:03 UTC
Loving `lsp-bridge` so far! Thanks!

I did notice a potential issue(?). At the moment, even if I try to toggle `corfu-doc`, nothing comes out
![image](https://user-images.githubusercontent.com/15933322/170247569-6cefac30-863d-4beb-be28-9e5c18e84124.png)

For reference, this is what it looks like with `lsp-mode`
![image](https://user-images.githubusercontent.com/15933322/170247878-67a85926-955f-400c-969e-2b1349cb2636.png)

Any ideas why it doesn't work with `lsp-bridge`?

**Comment by manateelazycat** [comment] 2022-05-25 11:13
Thanks for feedback, I was so tire recently.

I will have a look when I have free time.

Any PR are welcome.

**Comment by anonimitoraf** [comment] 2022-05-25 11:14
I see. Cool, I'll see if I can fix it!

**Comment by anonimitoraf** [comment] 2022-05-25 13:44
Sorry, I don't understand. Are you saying that's potentially what's causing corfu-doc to not work?

**Comment by manateelazycat** [comment] 2022-05-25 13:49
> Sorry, I don't understand. Are you saying that's potentially what's causing corfu-doc to not work?

Becasue we did parse ```doc``` content from textDocument/completion response, it's not a bug of corfu-doc

**Comment by anonimitoraf** [comment] 2022-05-25 21:36
AH! I see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ (the field `documentation` is missing). I'll try it out and make a PR, thanks!

**Comment by anonimitoraf** [comment] 2022-05-29 12:28
Actually, sorry I'm a bit lost on how I'd go about this.

My thoughts:
- Somehow register some sort of hook (via corfu or company) for when the selected candidate is changed - _TODO I need to find out how_
- Execute a "hover" request
- Somehow inject the "hover" response into the completion candidates list - _TODO I need to find out how_

Is this similar to what you were thinking?

**Comment by manateelazycat** [comment] 2022-05-29 13:53
1. You need find out how to hook corfu candidate selected
2. Then send `completionitem/resolve` request to python, details see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem_resolve
3. After receive response of `completionitem/resolve`, pick up `documentation` property from response json, show with corfu-doc

**Comment by manateelazycat** [comment] 2022-05-30 05:38
@anonimitoraf Has fixed by https://github.com/manateelazycat/lsp-bridge/commit/779bb42266ecf62b67614286051b959690e693bc

Need install corfu-doc.

**Closed by manateelazycat** 2022-05-30 05:38 UTC

**Comment by anonimitoraf** [comment] 2022-05-30 10:48
Oh damn thanks! Will learn from your code
