### ISSUE TITLE
outdated diagnostic

### ISSUE THREAD

**Issue by sawyerzheng** [manateelazycat/lsp-bridge#901] opened 2024-04-03 03:42 UTC
After lsp-bridge run for a long time. Sometimes, the diagnostic still dispaly there, even though the error is fixed and the lsp-bridge-diagnostic-list is empty.

![image](https://github.com/manateelazycat/lsp-bridge/assets/44355570/b59a6d9a-9fc1-48b0-9eac-e414a7222486)

**Comment by manateelazycat** [comment] 2024-04-03 04:38
Can you give me test code?

**Comment by sawyerzheng** [comment] 2024-04-03 05:04
Cannot give example code, because this behavior will disappear if I restart lsp-bridge or restart emacs.

This is a long existing problem, I fix it by restart `lsp-bridge-restart-process` every time.

**Comment by manateelazycat** [comment] 2024-04-05 02:19
When the lsp server has diagnostic information, it will call https://github.com/manateelazycat/lsp-bridge/blob/dfabfc818c688b38fce8c09323bd8ed9bcdd011f/core/lspserver.py#L603

Then lsp-bridge will call https://github.com/manateelazycat/lsp-bridge/blob/dfabfc818c688b38fce8c09323bd8ed9bcdd011f/core/fileaction.py#L303

Then call https://github.com/manateelazycat/lsp-bridge/blob/dfabfc818c688b38fce8c09323bd8ed9bcdd011f/core/fileaction.py#L317

Finally call https://github.com/manateelazycat/lsp-bridge/blob/dfabfc818c688b38fce8c09323bd8ed9bcdd011f/lsp-bridge-diagnostic.el#L185 to update the overlay of diagnostic information

Can you add print logs in the above places to see which function stopped when reproducing? As long as we can find the conditional judgment of the error, we can completely solve this problem.

**Comment by manateelazycat** [comment] 2024-04-13 04:13
@sawyerzheng

The diagnostic function should be developed first, and the hybrid multi-server function should be developed later.

The reason for diagnostic confusion is that when multiple LSP Servers are working at the same time (such as Python's default multi-server), different LSP Servers return diagnostic information at different times. If a Ticker is shared, the diagnostic information of some LSP Servers will be incorrectly discarded instead of being sent to Emacs to update diagnostic information.

Just update to the latest version

**Closed by manateelazycat** 2024-04-13 04:13 UTC
Labels: help wanted
